name: Convert NSE CSV to JSON

on:
  schedule:
    - cron: '00 16 * * *'  # 9:30 PM IST = 4:00 PM UTC
  workflow_dispatch:

jobs:
  convert-nse-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run conversion script
        run: |
          mkdir -p nse_data docs/nse_json
          python convert_all_reg_jsons.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update NSE JSON data: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
