name: Convert BSE CSV to JSON Daily

on:
  schedule:
    - cron: '00 16 * * *'  # 9:30 PM IST = 4:00 PM UTC
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run conversion script
        run: python convert_csv_to_json_bse.py

      - name: Commit and Push Changes to docs/bse_json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/bse_json
          git commit -m "✅ Auto-update BSE JSON data: $(date -u)" || echo "No changes to commit"
          git push
