name: Download NSE REG1_IND Data

on:
  schedule:
    - cron: '00 16 * * *'  # 9:30 PM IST = 4:00 PM UTC
  workflow_dispatch:

jobs:
  fetch-nse-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium requests webdriver-manager

      - name: Download NSE REG1_IND data
        run: python nse_surveillance_data/nse_download.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update NSE REG1_IND data: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
